sinatraメモアプリの提出
goruchanchan/sinatra_memo_app pull request #1
Opened 2022-07-16 11:51 UTC by goruchanchan

ご確認よろしくお願いします🙇‍♂️

2022-07-20 08:49 UTC, func09 requested changes
コード確認しました

* ファイル形式は CSV か JSON を検討してみてください
* ファイルの保存場所は public じゃない方がよいです
* RESTを意識したURLに見直してください

といった指摘になります。ご確認ください！

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +  './public/memos/'
データファイルの置き場所は `public` 配下だと ブラウザからアクセスできてしまい
セキュリティ的によろしくないので避けた方がよいです。

http://localhost:4567/memos/1/name.txt

例えば `./db` とかにすると良いと思います。

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +  content = f.read
name, content 以外の属性が増えた時に txtファイルが増えてしまうので
このファイル構成は避けた方がよさそうです。

構造化したデータのファイルフォーマットとしては

* CSV
* JSON

あたりが無難なので、検討してみてください。

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +  text.gsub(/&|<|>|"|'/, '&' => '&amp;', '<' => '&lt;', '>' => '&gt;', '"' => '&quot;', "\'" => '&#39;')
`Rack::Utils.escape_html` というメソッドも使えます。

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +post '/new' do
REST的なURLにするのであれば

* POST /

もしくは

* POST /memos

がよいと思います。`/memos` を採用するのであれば、URLは全体的に `/memos/*` の形式にすると良いと思います。

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +get '/show/:id' do
REST では URLに `show` は必要ないので

* GET /:id
* GET /memos/:id

のどちらかにしましょう。

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +delete '/:id/delete' do
RESTでは URLに `delete` は不要です。

2022-07-20 08:49 UTC, func09 commented on views/show.erb
> +  <td><form action="/<%= @memo_info[:id] %>/edit" method="post">
変更フォームを **表示するだけ** であれば、フォームではなく、リンクでOKです。

* GET /:id
* GET /memos/:id

へのリンクにしましょう。

2022-07-20 08:49 UTC, func09 commented on views/layout.erb
> +<% require './myapp.rb' %>
ここで `require` する必要はないので削除しましょう。
ちなみにここに `require` を入れた理由は何かありますか？

2022-07-20 08:49 UTC, func09 commented on myapp.rb
> +put '/:id/edit' do
アプリの挙動を見たところ `PUT` である必要はなく

* GET /:id/edit
* GET /memos/:id/edit

というような URLが良さそうです。

2022-07-20 12:46 UTC, goruchanchan commented on views/layout.erb
> +<% require './myapp.rb' %>
@func09 
ヘッダーファイル的に利用するのかと思い入れていました😅
layout.erbに入れておけば全部にインクルードできると思いここに記述しています💦
なくても動きました、、、消しておきます！！

2022-07-20 12:52 UTC, goruchanchan commented on myapp.rb
> +  './public/memos/'
`puclic` 以下じゃないと保存できないと思い込んでいました、、、
`./db`使わせてもらいます！

2022-07-20 14:09 UTC, goruchanchan commented on myapp.rb
> +  content = f.read
jsonこういうときに使うんですね！！ありがとうございます！使ってみます！

2022-07-20 14:19 UTC, goruchanchan commented on myapp.rb
> +  text.gsub(/&|<|>|"|'/, '&' => '&amp;', '<' => '&lt;', '>' => '&gt;', '"' => '&quot;', "\'" => '&#39;')
こんな便利なメソッドあるんですね！

2022-07-22 05:03 UTC, func09 approved these changes
LGTM~
ばっちりです！

2022-07-22 05:03 UTC, func09 commented on myapp.rb
> +  IO.write("#{load_memo_path}#{id}.json", JSON.dump({ id: id, name: name, content: content }))
👍

2022-07-22 13:11 UTC, merged